ALTER TABLE "StudioHour" ADD COLUMN "name" TEXT NOT NULL DEFAULT 'Turma';
ALTER TABLE "StudioHour" ALTER COLUMN "name" DROP DEFAULT;

ALTER TABLE "TimeSlot" ADD COLUMN "name" TEXT NOT NULL DEFAULT 'Turma';
ALTER TABLE "TimeSlot" ALTER COLUMN "name" DROP DEFAULT;
